#This compose file adds Airsonic https://airsonic.github.io/ to your stack
version: '3.7'
services:
  reverse-proxy:
    networks:
      - airsonic
  airsonic:
    image: airsonic/airsonic
    container_name: airsonic
    environment:
      - "JAVA_OPTS=-Dserver.use-forward-headers=true -Dserver.tomcat.protocol-header=X-Forwarded-Proto"
    volumes:
      - "~/Music:/airsonic/music:z"
      - "~/Podcasts:/airsonic/podcasts:z"
      - "~/.Playlists:/airsonic/playlists:z"
      - "airsonic-data:/airsonic/data"
    labels:
      - traefik.enable=true
      - traefik.port=4040
      - traefik.frontend.rule=Host:${AIRSONIC_DOMAIN:?Please copy template.env to .env and provide provide a value for AIRSONIC_DOMAIN}
      - traefik.frontend.redirect.regex=^http://${AIRSONIC_DOMAIN}/(.*)"
      - traefik.frontend.redirect.replacement=https://${AIRSONIC_DOMAIN}/$$1"
      - traefik.frontend.redirect.permanent=true
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.whiteList.useXForwardedFor=true
      - traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-Proto:https
      - traefik.docker.network=airsonic
      - traefik.default.protocol=http
      - com.ouroboros.enable=true
    networks:
      - airsonic
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://airsonic:4040 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  airsonic:

volumes:
  airsonic-data:
