#This compose file adds Draw.io https://draw.io to your stack
version: '3.7'
services:
  reverse-proxy:
    networks:
      - drawio
  drawio:
    image: fjudith/draw.io:latest
    container_name: drawio
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:${DRAWIO_DOMAIN:?Please copy template.env to .env and provide provide a value for DRAWIO_DOMAIN}
      - traefik.docker.network=drawio
      - traefik.default.protocol=http
      - com.ouroboros.enable=true
    networks:
      - drawio
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://drawio:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  drawio:
