#This compose file adds Heimdall Application Dashboard https://heimdall.site/ to your stack
version: '3.7'
services:
  reverse-proxy:
    networks:
      - heimdall
  mail-relay:
    networks:
      - heimdall
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    volumes:
      - heimdall-config:/config
    environment: #just an alternative syntax for specifying environment
      APP_NAME: ${HEIMDALL_APP_NAME:-"My Apps"}
      APP_URL: https://${HEIMDALL_DOMAIN:?Please copy template.env to .env and provide provide a value for HEIMDALL_DOMAIN}
      FORCE_HTTPS: "true"
      MAIL_HOST: ${HEIMDALL_SMTP_SERVER:-mail-relay}
      MAIL_PORT: ${HEIMDALL_SMTP_PORT:-25}
      #not used with mail-relay, but can be used
      MAIL_USERNAME: ${HEIMDALL_SMTP_USERNAME:-"null"}
      MAIL_PASSWORD: ${HEIMDALL_SMTP_PASSWORD:-"null"}
      MAIL_ENCRYPTION: ${HEIMDALL_SMTP_PASSWORD:-"null"}
      TZ: ${TZ}
      REDIS_HOST: heimdall-redis
      REDIS_PORT: 6379
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.backend=heimdall
      - traefik.frontend.rule=Host:${HEIMDALL_DOMAIN:?Please copy template.env to .env and provide provide a value for HEIMDALL_DOMAIN}
      - traefik.docker.network=heimdall
      - traefik.default.protocol=http
      - com.ouroboros.enable=true
    networks:
      - heimdall
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://heimdall || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 5s

  heimdall-redis:
    restart: unless-stopped
    container_name: heimdall-redis
    image: redis:latest
    networks:
      - heimdall
    labels:
      - "traefik.enable=false"
      - "com.ouroboros.enable=true"
    volumes:
      - heimdall-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

networks:
  heimdall:

volumes:
  heimdall-config:
  heimdall-redis:


